# This is a basic workflow to help you get started with Actions

name: Build and Publish Documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        poetry-version: ["1.3.1"]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        # By using poetry action, all dependencies are installed properly
        # from pyproject.toml and poetry.lock.
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Check installed libraries uinsg poetry.
        run: |
          poetry install
          poetry show
      - name: Build documentation
        # We cannot use poetry shell as it's not an interactive environment.
        # sphinx-build -M html doc/source doc/build
        run: |
          source $(poetry env info --path)/bin/activate
          pip list
      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: $${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build
